// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWWLzEpspyaYAPG_OMpwNtwTWFiNViDpM',
    appId: '1:499110728477:web:2028d2e683e341d6db07f4',
    messagingSenderId: '499110728477',
    projectId: 'inventoryapp-971ab',
    authDomain: 'inventoryapp-971ab.firebaseapp.com',
    storageBucket: 'inventoryapp-971ab.firebasestorage.app',
    measurementId: 'G-JHFT59B3K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4-eoSvl6gjoVtS1j-APw8_NFUMCdcKE',
    appId: '1:499110728477:android:40ba6b79c2a8ea39db07f4',
    messagingSenderId: '499110728477',
    projectId: 'inventoryapp-971ab',
    storageBucket: 'inventoryapp-971ab.firebasestorage.app',
  );

}